### ISSUE TITLE
Getting cURL error 60: SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by pratiksoni9** [craftsys/msg91-php#12]
**Describe the bug**
SSL Certificate issue

**To Reproduce**
A clear test case to reproduce the bug

**Expected behavior**

**Additional context**

**Comment by sudkumar** [comment]
Thank you for reporting.

Please provide a reproduction code sample so that I can look into it.

Few things you might want to check:

- Check your SSL certificate in your server
- Check out the Guzzlehttp Client library for more details on why you might be getting this issue

Feel free to reopen with a reproduction case.
