### ISSUE TITLE
authkey is invalid error occurs when trying to resend otp

### ISSUE THREAD

**Issue by sahilsethchd** [craftsys/msg91-php#6]
**Describe the bug**

**To Reproduce**
A clear test case to reproduce the bug

**Expected behavior**

**Additional context**

**Comment by sudkumar** [comment]
Provide some context on the way you are resending the OTPs along with error responses.

**Comment by sahilsethchd** [comment]
Steps to recreate:

Create a new Laravel 8 project
Install msg91-laravel
Set the msg91 key with the appropriate values in config/services.php
In Api Controller, run Msg91::otp()->to(91xxxxxxxxxx)->send(); to receive the OTP. Then run Msg91::otp()->to(918888888888)->resend(); to resend. 
The resendstatement throws the exception "Invalid authkey"

If you need additional information please let me know.

**Comment by sudkumar** [comment]
Hey @sahilsethchd Just created a PR for this fix. The issue was related to request's content type headers. 

Some apis requires `form-data` (resend and verify otps) while other requires `json` (send otp). Earlier resend OTP api was expecting json.

I have tested it on my end but you should test it as well and then I will merge.

Go to `/vendor/craftsys/msg91-php/src/OTP/ResendRequest.php` and set the `content_type` property as follows

```diff
class ResendRequest extends Request
{
    protected $url = URLs::OTP_RESEND_URL;
+
+   protected $content_type = \GuzzleHttp\RequestOptions::FORM_PARAMS;
```

If it fixed the problem, please update me here and I will push a new release.

**Comment by sahilsethchd** [comment]
Thanks for your reply. It resolved the issue.

Well, I checked the docs for MSG91 @ https://docs.msg91.com/p/tf9GTextN/e/7WESqQ4RLu/MSG91

It is clearly mentioned that they accept params in form-data (sendotp, resendotp and verifyotp) where as json required for sending Sms via flow.
